/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.BanHangDao;
import DATABASE.DatabaseHelper;
import ENTITY.ChiTietSanPham;
import ENTITY.HoaDon;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TieuLong
 */
public class QuanLyBanHang extends javax.swing.JPanel {

    private List<HoaDon> danhSachHoaDonCho;
    private ChiTietSanPham ctsp = new ChiTietSanPham();
    private DefaultTableModel dtm = new DefaultTableModel();
    private BanHangDao ctspsi = new BanHangDao();
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
    private List<ChiTietSanPham> list = new ArrayList<>();
    private DefaultTableModel dtmSanPham;
    private DefaultTableModel dtmGioHang;
    private DefaultTableModel dtmHoaDonCho;
    private BanHangDao banHangDao;
    private String tenNhanVien;

    /**
     * Creates new form QuanLyBanHang
     */
    public QuanLyBanHang() {
        initComponents();
        setVisible(true);
        dtm = (DefaultTableModel) tblSanPham.getModel();
        LoadCbbLocKD(ctspsi.getListKieuDang1());
        LoadCbbLocS(ctspsi.getListSize1());
        list = ctspsi.getAll();
        showData(list);
        tblSanPham.setEnabled(false);
        banHangDao = new BanHangDao();
        dtmSanPham = (DefaultTableModel) tblSanPham.getModel();
        dtmGioHang = (DefaultTableModel) tblGioHang.getModel();
        dtmHoaDonCho = (DefaultTableModel) jTableHoaDonCho.getModel();
        loadSanPham();
        tblSanPham.setEnabled(false);
        jButtonTaoHoaDon.setEnabled(true);
        jTextFieldTenNhanVien.setEditable(false);
        jTextFieldMaHoaDon.setEditable(false);
        jTextFieldTongTien.setEditable(false);

    }

//    private void fillTableGioHang(List<HoaDonChiTiet> list) {
//        DefaultTableModel dtm = new DefaultTableModel();
//        dtm = (DefaultTableModel) tblSanPham.getModel();
//        dtm.setRowCount(0);
//        for (HoaDonChiTiet x : list) {
//            dtm.addRow(new Object[]{x.getIdctsp(), x.getIdctsp(), x.getIdctsp(), x.getSoluong()});
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelQUANLYBANHANG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHoaDonCho = new javax.swing.JTable();
        jLabelHoaDonCho = new javax.swing.JLabel();
        jLabelGioHang = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jLabelSanPham = new javax.swing.JLabel();
        jLabelSDTKhachHang = new javax.swing.JLabel();
        jTextFieldSDTKhachHang = new javax.swing.JTextField();
        jLabelTenKhachHang = new javax.swing.JLabel();
        jTextFieldTenKhachHang = new javax.swing.JTextField();
        jButtonTimKiemKhachHang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonThemMoiKhachHang = new javax.swing.JButton();
        jButtonTreoHoaDon = new javax.swing.JButton();
        cbbKieu = new javax.swing.JComboBox<>();
        cbbSize = new javax.swing.JComboBox<>();
        jLabelTenSanPham = new javax.swing.JLabel();
        txtTk = new javax.swing.JTextField();
        jButtonTimTenSanPham = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabelSanPham1 = new javax.swing.JLabel();
        jLabelSanPham2 = new javax.swing.JLabel();
        jButtonTaoHoaDon = new javax.swing.JButton();
        jLabelMaHoaDon = new javax.swing.JLabel();
        jTextFieldTongTien = new javax.swing.JTextField();
        jLabelTongTien = new javax.swing.JLabel();
        jTextFieldTienKhachDua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTienThua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxHinhThucThanhToan = new javax.swing.JComboBox<>();
        jButtonThanhToan = new javax.swing.JButton();
        jButtonHuyThanhToan = new javax.swing.JButton();
        jTextFieldTenNhanVien = new javax.swing.JTextField();
        jTextFieldMaHoaDon = new javax.swing.JTextField();
        jLabelTenNhanVien = new javax.swing.JLabel();
        jLabelThongTinHoaDon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxGiamGia = new javax.swing.JComboBox<>();

        jLabelQUANLYBANHANG.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelQUANLYBANHANG.setText("QUẢN LÝ BÁN HÀNG");

        jTableHoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Tạo Hóa Đơn", "Tổng Tiền", "Trạng Thái"
            }
        ));
        jScrollPane1.setViewportView(jTableHoaDonCho);

        jLabelHoaDonCho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHoaDonCho.setText("Hóa Đơn Chờ");

        jLabelGioHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelGioHang.setText("Giỏ Hàng");

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên sản phẩm", "Size", "Đơn giá", "Số lượng"
            }
        ));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        jLabelSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSanPham.setText("Sản Phẩm");

        jLabelSDTKhachHang.setText("SDT Khách Hàng");

        jLabelTenKhachHang.setText("Tên Khách Hàng");

        jButtonTimKiemKhachHang.setText("Tìm Kiếm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Khách Hàng");

        jButtonThemMoiKhachHang.setText("Thêm Mới");

        jButtonTreoHoaDon.setText("Treo Hóa Đơn");
        jButtonTreoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreoHoaDonActionPerformed(evt);
            }
        });

        cbbKieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKieuActionPerformed(evt);
            }
        });

        cbbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSizeActionPerformed(evt);
            }
        });

        jLabelTenSanPham.setText("Tìm Tên Sản Phẩm");

        txtTk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTkMouseClicked(evt);
            }
        });

        jButtonTimTenSanPham.setText("Tìm");
        jButtonTimTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimTenSanPhamActionPerformed(evt);
            }
        });

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên sản phẩm", "Size", "Kiểu Dáng", "Đơn Giá", "Số Lượng"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        jLabelSanPham1.setText("Size");

        jLabelSanPham2.setText("Kiểu Dáng");

        jButtonTaoHoaDon.setText("Tạo Hóa Đơn");
        jButtonTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoHoaDonActionPerformed(evt);
            }
        });

        jLabelMaHoaDon.setText("Mã Hóa Đơn");

        jTextFieldTongTien.setEditable(false);

        jLabelTongTien.setText("Tổng Tiền");

        jLabel6.setText("Tiền Khách Đưa");

        jLabel7.setText("Tiền Thừa");

        jLabel8.setText("Hình Thức TT");

        jComboBoxHinhThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Chuyển Khoản" }));
        jComboBoxHinhThucThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHinhThucThanhToanActionPerformed(evt);
            }
        });

        jButtonThanhToan.setText("Thanh Toán");
        jButtonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThanhToanActionPerformed(evt);
            }
        });

        jButtonHuyThanhToan.setText("Hủy Thanh Toán");
        jButtonHuyThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyThanhToanActionPerformed(evt);
            }
        });

        jTextFieldTenNhanVien.setEditable(false);

        jTextFieldMaHoaDon.setEditable(false);

        jLabelTenNhanVien.setText("Tên Nhân Viên");

        jLabelThongTinHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelThongTinHoaDon.setText("Thông Tin Hóa Đơn");

        jLabel2.setText("Giảm giá");

        jComboBoxGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "5%", "10%", "15%", "20%", "25%", "30%", "35%", "40%", "45%", "50%" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGioHang)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSDTKhachHang)
                                            .addComponent(jLabelTenKhachHang))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldSDTKhachHang)
                                            .addComponent(jTextFieldTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonTimKiemKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonThemMoiKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                            .addComponent(jButtonTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonTreoHoaDon)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabelTenSanPham))
                                    .addComponent(jLabelSanPham))
                                .addGap(18, 18, 18)
                                .addComponent(txtTk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonTimTenSanPham))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHoaDonCho)
                                .addGap(288, 288, 288)
                                .addComponent(jLabelQUANLYBANHANG))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelSanPham2)
                            .addGap(18, 18, 18)
                            .addComponent(cbbKieu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabelSanPham1)
                            .addGap(18, 18, 18)
                            .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelThongTinHoaDon)
                            .addComponent(jLabelTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTenNhanVien)
                            .addComponent(jTextFieldMaHoaDon)
                            .addComponent(jTextFieldTongTien)
                            .addComponent(jTextFieldTienKhachDua)
                            .addComponent(jTextFieldTienThua)
                            .addComponent(jComboBoxHinhThucThanhToan, 0, 176, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonThanhToan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHuyThanhToan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelHoaDonCho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelQUANLYBANHANG)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabelGioHang)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelThongTinHoaDon))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTenNhanVien)
                            .addComponent(jTextFieldTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelSDTKhachHang)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelTenKhachHang)
                                                .addComponent(jTextFieldTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonThemMoiKhachHang)))
                                        .addComponent(jTextFieldSDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonTimKiemKhachHang)
                                        .addGap(34, 34, 34)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTreoHoaDon)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTaoHoaDon)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextFieldMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBoxGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMaHoaDon)
                                        .addGap(60, 60, 60)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTongTien)
                                    .addComponent(jTextFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBoxHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHuyThanhToan)
                            .addComponent(jButtonThanhToan))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSanPham1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTenSanPham)
                                .addComponent(txtTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonTimTenSanPham)
                                .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbKieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSanPham2)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelSanPham)
                        .addGap(5, 5, 5)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hienThiHoaDonCho() {
        dtm.setRowCount(0);
        // Thêm 4 hóa đơn chờ vào
        for (HoaDon hoaDon : danhSachHoaDonCho) {
            Object[] row = new Object[]{
                hoaDon.getMahd(),
                hoaDon.getNgayTao(),
                hoaDon.getTongTien(),
                hoaDon.getTrangThai()
            };
            dtm.addRow(row);
        }
    }

    private void showData(List<ChiTietSanPham> list) {
        dtm.setRowCount(0);
        for (ChiTietSanPham ctsp : list) {
            dtm.addRow(new Object[]{ctsp.getMactsp(), ctsp.getIdsp(), ctsp.getIdsize(), ctsp.getIdkieu(), ctsp.getDongia(), ctsp.getSoluong()});
        }
    }

    private void LoadCbbLocKD(List<String> list) {
        dcbm = (DefaultComboBoxModel) cbbKieu.getModel();
        for (String string : list) {
            dcbm.addElement(string);
        }
    }

    private void LoadCbbLocS(List<String> list) {
        dcbm = (DefaultComboBoxModel) cbbSize.getModel();
        for (String string : list) {
            dcbm.addElement(string);
        }
    }

    private void jButtonTimTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimTenSanPhamActionPerformed
        // TODO add your handling code here:
        String tk = txtTk.getText(); // Lấy dữ liệu từ trường văn bản
        // Kiểm tra xem trường văn bản có dữ liệu hay không
        if (!tk.isEmpty()) { // Nếu có dữ liệu
            ctspsi.Tk(tk);
            list = ctspsi.Tk(tk);
            showData(list);
        } else { // Nếu không có dữ liệu
            JOptionPane.showMessageDialog(null, "Vui lòng nhập dữ liệu để tìm"); // Hiển thị thông báo
        }
    }//GEN-LAST:event_jButtonTimTenSanPhamActionPerformed

    private void txtTkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTkMouseClicked
        // TODO add your handling code here:
        txtTk.setText("");
        list = ctspsi.getAll();
        showData(list);
    }//GEN-LAST:event_txtTkMouseClicked

    private void cbbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSizeActionPerformed
        // TODO add your handling code here:
        String ten = cbbSize.getSelectedItem().toString();
        ctspsi.Loc1(ten);
        list = ctspsi.Loc1(ten);
        showData(list);
    }//GEN-LAST:event_cbbSizeActionPerformed

    private void cbbKieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKieuActionPerformed
        // TODO add your handling code here:
        String ma = cbbKieu.getSelectedItem().toString();
        ctspsi.Loc1(ma);
        list = ctspsi.Loc1(ma);
        showData(list);
    }//GEN-LAST:event_cbbKieuActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked

        int rowIndex = tblSanPham.getSelectedRow();
        DefaultTableModel model1 = (DefaultTableModel) tblSanPham.getModel();

        // Chỉ định chỉ số các cột bạn quan tâm
        int[] columnsOfInterest = {0, 1, 5, 4}; // Ví dụ: lấy cột 0, 1, 5 và 4

        // Kiểm tra xem có dòng được chọn không
        if (rowIndex != -1) {
            // Lấy dữ liệu từ các cột quan tâm
            Object[] rowData = new Object[columnsOfInterest.length];
            for (int i = 0; i < columnsOfInterest.length; i++) {
                int columnIndex = columnsOfInterest[i];
                rowData[i] = model1.getValueAt(rowIndex, columnIndex);
            }

            // Yêu cầu người dùng nhập số lượng
            String quantityString = JOptionPane.showInputDialog(null, "Nhập số lượng:", "Nhập số lượng", JOptionPane.PLAIN_MESSAGE);
            if (quantityString != null && !quantityString.isEmpty()) {
                try {
                    int quantity = Integer.parseInt(quantityString);
                    int currentQuantity = (int) model1.getValueAt(rowIndex, columnsOfInterest[3]); // Lấy dữ liệu từ cột số lượng
                    if (quantity <= currentQuantity && quantity <= 30) { // Kiểm tra số lượng nhập vào không vượt quá 30
                        // Tạo DefaultTableModel cho jTableGioHang nếu chưa có
                        DefaultTableModel model2 = (DefaultTableModel) tblGioHang.getModel();
                        if (model2.getRowCount() == 0) {
                            // Thêm các cột vào bảng jTableGioHang
                            for (int i = 0; i < columnsOfInterest.length; i++) {
                                int columnIndex = columnsOfInterest[i];
                                model2.addColumn(model1.getColumnName(columnIndex));
                            }
                            // Thêm cột mới để hiển thị số lượng nhập vào
                            model2.addColumn("Số lượng nhập");
                        }

                        // Thêm dữ liệu vào jTableGioHang từ hàng đầu tiên
                        Object[] newData = new Object[rowData.length + 1];
                        System.arraycopy(rowData, 0, newData, 0, rowData.length); // Sao chép dữ liệu từ rowData
                        newData[rowData.length] = quantity; // Thêm số lượng nhập vào cuối mảng newData
                        model2.insertRow(0, newData); // Thêm dữ liệu mới vào bảng
                    } else {
                        JOptionPane.showMessageDialog(null, "Số lượng nhập vào phải nhỏ hơn hoặc bằng 30 và không vượt quá số lượng hiện có của sản phẩm", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }


    private void jButtonTreoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreoHoaDonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonTreoHoaDonActionPerformed

    private void jComboBoxHinhThucThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHinhThucThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHinhThucThanhToanActionPerformed

    private void jButtonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThanhToanActionPerformed
        try {
            // Lưu thông tin hóa đơn và hóa đơn chi tiết vào cơ sở dữ liệu
            // Cập nhật thông tin hóa đơn
            String sqlHoaDon = "UPDATE HOADON SET Ngaytao = ?, NgayChinhSua = ?, TrangThai = ? WHERE Mahd = ?";
            // Thực hiện câu lệnh SQL để cập nhật thông tin hóa đơn
            // Lưu thông tin hóa đơn
            Connection connection = DatabaseHelper.getConnection();
            PreparedStatement preparedStatementHoaDon = connection.prepareStatement(sqlHoaDon);
            preparedStatementHoaDon.setDate(1, new java.sql.Date(new Date().getTime())); // Ngày tạo hóa đơn
            preparedStatementHoaDon.setDate(2, new java.sql.Date(new Date().getTime())); // Ngày chỉnh sửa hóa đơn
            preparedStatementHoaDon.setString(3, "Đã thanh toán"); // Trạng thái hóa đơn
            preparedStatementHoaDon.setString(4, jTextFieldMaHoaDon.getText()); // Mã hóa đơn

            // Thực hiện cập nhật thông tin hóa đơn
            int rowsAffectedHoaDon = preparedStatementHoaDon.executeUpdate();

            // Lưu thông tin hóa đơn chi tiết
            String sqlHoaDonChiTiet = "INSERT INTO HOADONCHITIET (Mahd, Masanpham, Soluong, Dongia) VALUES (?, ?, ?, ?)";
            PreparedStatement preparedStatementHoaDonChiTiet = connection.prepareStatement(sqlHoaDonChiTiet);

            // Lưu từng dòng trong jTableGioHang vào cơ sở dữ liệu
            for (int i = 0; i < tblGioHang.getRowCount(); i++) {
                String maSanPham = tblGioHang.getValueAt(i, 0).toString();
                int soLuong = Integer.parseInt(tblGioHang.getValueAt(i, 2).toString());
                double donGia = Double.parseDouble(tblGioHang.getValueAt(i, 3).toString());
                preparedStatementHoaDonChiTiet.setString(1, jTextFieldMaHoaDon.getText()); // Mã hóa đơn
                preparedStatementHoaDonChiTiet.setString(2, maSanPham); // Mã sản phẩm
                preparedStatementHoaDonChiTiet.setInt(3, soLuong); // Số lượng
                preparedStatementHoaDonChiTiet.setDouble(4, donGia); // Đơn giá
                preparedStatementHoaDonChiTiet.executeUpdate();
            }

            // Đóng kết nối và hiển thị thông báo cho người dùng
            connection.close();
            JOptionPane.showMessageDialog(this, "Hóa đơn đã được lưu vào cơ sở dữ liệu.");
            // Làm sạch giao diện
            jTextFieldTenNhanVien.setText("");
            jTextFieldMaHoaDon.setText("");
            jTextFieldTongTien.setText("");
            dtmGioHang.setRowCount(0);
        } catch (SQLException | NumberFormatException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu hóa đơn vào cơ sở dữ liệu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonThanhToanActionPerformed

    private void jButtonHuyThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyThanhToanActionPerformed
        try {
            // Xóa thông tin hóa đơn, hóa đơn chi tiết tương ứng với hóa đơn
            Connection connection = DatabaseHelper.getConnection();
            // Xóa thông tin hóa đơn
            String sqlHoaDon = "DELETE FROM HOADON WHERE Mahd = ?";
            PreparedStatement preparedStatementHoaDon = connection.prepareStatement(sqlHoaDon);
            preparedStatementHoaDon.setString(1, jTextFieldMaHoaDon.getText());
            preparedStatementHoaDon.executeUpdate();

            // Xóa thông tin hóa đơn chi tiết
            String sqlHoaDonChiTiet = "DELETE FROM HOADONCHITIET WHERE Idhd = ?";
            PreparedStatement preparedStatementHoaDonChiTiet = connection.prepareStatement(sqlHoaDonChiTiet);
            preparedStatementHoaDonChiTiet.setString(1, jTextFieldMaHoaDon.getText());
            preparedStatementHoaDonChiTiet.executeUpdate();

            // Đóng kết nối và hiển thị thông báo cho người dùng
            connection.close();
            JOptionPane.showMessageDialog(this, "Hóa đơn đã được xóa khỏi cơ sở dữ liệu.");
            // Làm sạch giao diện
            jTextFieldTenNhanVien.setText("");
            jTextFieldMaHoaDon.setText("");
            jTextFieldTongTien.setText("");
            dtmGioHang.setRowCount(0);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa hóa đơn từ cơ sở dữ liệu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyBanHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonHuyThanhToanActionPerformed

    private void displayEmployeeNameFromDatabase() throws Exception {
        try {
            // Kết nối đến cơ sở dữ liệu
            Connection connection = DatabaseHelper.getConnection();
            // Tạo câu truy vấn SQL để lấy tên nhân viên từ bảng NHANVIEN dựa trên tên tài khoản từ bảng TAIKHOAN
            String sql = "SELECT NV.Ten FROM NHANVIEN NV JOIN TAIKHOAN TK ON NV.MataiKhoan = TK.Mataikhoan WHERE TK.Tentaikhoan = ?";
            // Tạo PreparedStatement
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            // Đặt tham số cho câu truy vấn
            preparedStatement.setString(1, Dashboard.taiKhoan.getTentaikhoan());
            // Thực thi câu truy vấn
            ResultSet resultSet = preparedStatement.executeQuery();
            // Kiểm tra xem có kết quả trả về không
            if (resultSet.next()) {
                // Lấy tên nhân viên từ kết quả trả về và hiển thị trong JTextFieldTenNhanVien
                String tenNhanVien = resultSet.getString("Ten");
                jTextFieldTenNhanVien.setText(tenNhanVien);
            }
            // Đóng kết nối
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            throw new Exception("Lỗi khi lấy tên nhân viên từ cơ sở dữ liệu.");
        }
    }

    // Quản lý kết nối và tài nguyên một cách an toàn
    private boolean createNewInvoice(String idHoaDon, String maHoaDon, Date ngayTao, Integer trangThai) throws Exception {
        try (Connection connection = DatabaseHelper.getConnection()) {
            String sql = "INSERT INTO HOADON (Id, Mahd, Ngaytao, TrangThai) VALUES (?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setString(1, idHoaDon);
                preparedStatement.setString(2, maHoaDon);
                preparedStatement.setDate(3, new java.sql.Date(ngayTao.getTime()));
                preparedStatement.setInt(4, trangThai);
                int rowsAffected = preparedStatement.executeUpdate();
                return rowsAffected > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public boolean createNewInvoiceDetail(String idHoaDonChiTiet, String idHoaDon, Date ngayTao, Integer trangThai) throws Exception {
        try (Connection connection = DatabaseHelper.getConnection()) {
            String sql = "INSERT INTO HOADONCHITIET (Id, Idhd, Ngaytao, TrangThai) VALUES (?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setString(1, idHoaDon);
                preparedStatement.setString(2, idHoaDon);
                preparedStatement.setDate(3, new java.sql.Date(ngayTao.getTime()));
                preparedStatement.setInt(4, trangThai);
                int rowsAffected = preparedStatement.executeUpdate();
                return rowsAffected > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }


    private void jButtonTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoHoaDonActionPerformed
        tblSanPham.setEnabled(true);
        try {
            // Hiển thị tên nhân viên từ cơ sở dữ liệu
            displayEmployeeNameFromDatabase();
            // Tạo hóa đơn mới và lưu vào cơ sở dữ liệu
            String idHoaDon = UUID.randomUUID().toString();
            String maHoaDon = "HD" + UUID.randomUUID().toString();
            Date ngayTao = new Date();
            Integer trangThai = 0;
            // Tạo hóa đơn CT mới và lưu vào cơ sở dữ liệu
            String idHoaDonCT = UUID.randomUUID().toString();
            String idMaHoaDon = idHoaDon;
            Date ngayTaoCT = ngayTao;
            Integer trangThaiCT = 0;
            boolean success1 = createNewInvoice(idHoaDon, maHoaDon, ngayTao, trangThai);
            boolean success2 = createNewInvoiceDetail(idHoaDonCT, idMaHoaDon, ngayTaoCT, trangThaiCT); // Sửa ở đây
            if (success1 && success2) {
//                JOptionPane.showMessageDialog(this, "Hóa đơn mới đã được tạo thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldMaHoaDon.setText(maHoaDon);
                jTextFieldTenNhanVien.setText("");
                jTextFieldTongTien.setText("");
                dtmGioHang.setRowCount(0);
                tblSanPham.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không thể tạo hóa đơn mới. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi tạo hóa đơn mới. Vui lòng thử lại sau.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTaoHoaDonActionPerformed
    private void loadSanPham() {
        List<ChiTietSanPham> listSanPham = banHangDao.getAll();
        dtmSanPham.setRowCount(0);
        for (ChiTietSanPham ctsp : listSanPham) {
            dtmSanPham.addRow(new Object[]{ctsp.getMactsp(), ctsp.getIdsp(), ctsp.getIdsize(), ctsp.getIdkieu(), ctsp.getDongia(), ctsp.getSoluong()});
        }
    }

    private void loadHoaDonCho(List<ChiTietSanPham> gioHang) {
        HoaDon hoaDon = new HoaDon();
        hoaDon.setMahd(jTextFieldMaHoaDon.getText());
        hoaDon.setIdnv(tenNhanVien);
//        hoaDon.setChiTietSanPham(gioHang);
        dtmHoaDonCho.addRow(new Object[]{hoaDon.getMahd(), hoaDon.getId(), hoaDon.getTongTien()});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbKieu;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JButton jButtonHuyThanhToan;
    private javax.swing.JButton jButtonTaoHoaDon;
    private javax.swing.JButton jButtonThanhToan;
    private javax.swing.JButton jButtonThemMoiKhachHang;
    private javax.swing.JButton jButtonTimKiemKhachHang;
    private javax.swing.JButton jButtonTimTenSanPham;
    private javax.swing.JButton jButtonTreoHoaDon;
    private javax.swing.JComboBox<String> jComboBoxGiamGia;
    private javax.swing.JComboBox<String> jComboBoxHinhThucThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGioHang;
    private javax.swing.JLabel jLabelHoaDonCho;
    private javax.swing.JLabel jLabelMaHoaDon;
    private javax.swing.JLabel jLabelQUANLYBANHANG;
    private javax.swing.JLabel jLabelSDTKhachHang;
    private javax.swing.JLabel jLabelSanPham;
    private javax.swing.JLabel jLabelSanPham1;
    private javax.swing.JLabel jLabelSanPham2;
    private javax.swing.JLabel jLabelTenKhachHang;
    private javax.swing.JLabel jLabelTenNhanVien;
    private javax.swing.JLabel jLabelTenSanPham;
    private javax.swing.JLabel jLabelThongTinHoaDon;
    private javax.swing.JLabel jLabelTongTien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableHoaDonCho;
    private javax.swing.JTextField jTextFieldMaHoaDon;
    private javax.swing.JTextField jTextFieldSDTKhachHang;
    private javax.swing.JTextField jTextFieldTenKhachHang;
    private javax.swing.JTextField jTextFieldTenNhanVien;
    private javax.swing.JTextField jTextFieldTienKhachDua;
    private javax.swing.JTextField jTextFieldTienThua;
    private javax.swing.JTextField jTextFieldTongTien;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtTk;
    // End of variables declaration//GEN-END:variables

}
